### ISSUE TITLE
does not work with category requests

### ISSUE THREAD

**Issue by sethvanstaden91** [shahin8r/comments-posts-wp-api#1]
Hey this is a very awesome plugin and it solved the comment problem on getting comments from all posts but it does not seem to include comments when making a call for a specific category, such as:
http://www.example.com/tna_wp/wp-json/posts?filter[category_name]=example&withcomments

**Comment by shahin8r** [comment]
Glad you liked it. :)

Just tested it on a local site and for me it's working fine with `/wp-json/posts?filter[category_name]=test&withcomments`.

![image](https://cloud.githubusercontent.com/assets/4785263/9474078/af4af232-4b5e-11e5-8135-3a9f8c25aeca.png)

What version of Wordpress and the WP API plugin are you using?
